const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Clipboard,
		C3.Behaviors.Anchor,
		C3.Plugins.HTMLElement,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardFetchScoped,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.Button.Cnds.PickByUID,
		C3.Plugins.Eponesh_GameScore.Cnds.OnLeaderboardFetch,
		C3.Plugins.Eponesh_GameScore.Cnds.LeaderboardEachPlayer,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerIndex,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerName,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerPosition,
		C3.Plugins.Eponesh_GameScore.Exps.LeaderboardCurPlayerScore,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerAdd,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardSetRecord,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardPublishRecord,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Touch.Cnds.CompareOrientation,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.HTMLElement.Acts.SetVisible,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Eponesh_GameScore.Cnds.VariablesCompare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerName,
		C3.Plugins.Eponesh_GameScore.Exps.PlayersCurPlayerID,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerID
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{GamePush: 0},
	{leaders: 0},
	{Touch: 0},
	{Браузер: 0},
	{text2_: 0},
	{БуферОбмена: 0},
	{score_txt: 0},
	{Якорь: 0},
	{Текст2: 0},
	{Loading_Element: 0},
	{technical_work_element: 0},
	{leadername_txt: 0},
	{TEXT: 0},
	{Player_Username_txt: 0},
	{Player_ID_txt: 0},
	{fc15c272ac709ac76e60d0898f65c3b: 0},
	{Picsart_260114_: 0},
	{Refresh_button: 0},
	{Leaderbord_button: 0},
	{leaderid_txt: 0},
	{Button: 0},
	{leaderbalance_txt2: 0},
	{scroll_x: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	GamePush: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	leaders: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Браузер: class extends self.IInstance {},
	text2_: class extends self.ITextInstance {},
	БуферОбмена: class extends self.IInstance {},
	score_txt: class extends self.ITextInstance {},
	Текст2: class extends self.ITextInstance {},
	Loading_Element: class extends self.IHTMLElementInstance {},
	technical_work_element: class extends self.IHTMLElementInstance {},
	leadername_txt: class extends self.ITextInstance {},
	TEXT: class extends self.ITextInstance {},
	Player_Username_txt: class extends self.ITextInstance {},
	Player_ID_txt: class extends self.ITextInstance {},
	fc15c272ac709ac76e60d0898f65c3b: class extends self.ISpriteInstance {},
	Picsart_260114_: class extends self.ISpriteInstance {},
	Refresh_button: class extends self.IButtonInstance {},
	Leaderbord_button: class extends self.IButtonInstance {},
	leaderid_txt: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	leaderbalance_txt2: class extends self.ITextInstance {}
}